=encoding utf-8


=head1 Revision history for ip2proxy



=head2 3.4.0  -- 2025-02-20



=over


=item *

Added support for fraud score.


=back


=head2 3.3.3  -- 2024-12-12



=over


=item *

Fixed error with IPv6 IP when using IPv4 BIN.

=item *

Fixed number overflow.


=back


=head2 3.3.2  -- 2023-03-07



=over


=item *

Fixed overflow issue.


=back


=head2 3.3.1  -- 2022-07-26



=over


=item *

Fixed undeclared variable.


=back


=head2 3.3.0  -- 2022-07-05



=over


=item *

Reduced file I/O.


=back


=head2 3.2.0  -- 2021-12-22



=over


=item *

Initial version.

=back

